<?php

return array (
  'name' => 'Resistor Noise Calculator',
  'title' => 'Resistor Noise Calculator',
  'desc' => 'Calculate the thermal noise voltage generated by a resistor over a given bandwidth.',
  'seo_title' => 'Resistor Noise Calculator | Thermal Noise Voltage',
  'seo_desc' => 'Calculate resistor thermal noise voltage from resistance and bandwidth with a simple physics calculator.',
);
