<?php

return array (
  'name' => 'Joule Heating Calculator',
  'title' => 'Joule Heating Calculator',
  'desc' => 'Calculate heat generated by electrical current using voltage, resistance, current, and time.',
  'seo_title' => 'Joule Heating Calculator | Calculate Electrical Heat',
  'seo_desc' => 'Calculate joule heating from voltage, current, resistance, and time with a simple physics calculator.',
);
